name: speechllm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - accelerate=1.7.0=pyhe01879c_0
  - aiohappyeyeballs=2.4.4=py313h06a4308_0
  - aiohttp=3.11.10=py313h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.6.0=py313h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=h865e1df_2
  - attrs=24.3.0=py313h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=openblas
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py313h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py313h06a4308_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-version=12.4=hbda6634_3
  - cudnn=9.1.1.17=cuda12_1
  - datasets=2.14.4=pyhd8ed1ab_0
  - deprecated=1.2.13=py313h06a4308_0
  - dill=0.3.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py313h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py313h5eee18b_0
  - fsspec=2025.3.2=py313h7040dfc_0
  - gflags=2.2.2=h6a678d5_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py313h06a4308_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py313h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - huggingface_hub=0.31.2=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - importlib-metadata=8.5.0=py313h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jinja2=3.1.6=py313h06a4308_0
  - jiwer=3.0.5=pyhe01879c_2
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.1.0=h767d61c_2
  - libgrpc=1.71.0=h2d74bed_0
  - libidn2=2.3.4=h5eee18b_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnvjitlink=12.4.127=h99ab3db_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=hc99497a_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtorch=2.5.1=gpu_cuda124_he07d216_204
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - lightning-utilities=0.11.9=py313h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.7.1=h9153a54_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - mkl=2025.0.0=hacee8c2_941
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py313h06a4308_0
  - multidict=6.1.0=py313h5eee18b_0
  - multiprocess=0.70.15=py313h06a4308_0
  - nccl=2.21.5.1=ha515578_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py313h06a4308_0
  - nomkl=3.0=0
  - numexpr=2.10.1=py313hd28fd6d_0
  - numpy=2.2.5=py313h3d1d590_0
  - numpy-base=2.2.5=py313hc428782_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.16=h5eee18b_0
  - opentelemetry-api=1.30.0=py313h06a4308_0
  - orc=2.1.1=hd396ef6_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313h6a678d5_0
  - peft=0.15.2=pyhd8ed1ab_0
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py313h06a4308_0
  - propcache=0.3.1=py313h5eee18b_0
  - protobuf=5.29.3=py313he621ea3_0
  - psutil=5.9.0=py313h5eee18b_1
  - pyarrow=19.0.0=py313h6a678d5_1
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h5eee18b_0
  - python_abi=3.13=0_cp313
  - pytorch-lightning=2.5.1.post0=pyh2a12c56_0
  - pytz=2024.1=py313h06a4308_0
  - pyyaml=6.0.2=py313h5eee18b_0
  - rapidfuzz=3.12.1=py313h6a678d5_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py313h5eee18b_0
  - requests=2.32.3=py313h06a4308_1
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.5.3=py313h8a85203_0
  - sentry-sdk=2.18.0=py313h06a4308_0
  - setproctitle=1.2.2=py313h5eee18b_2
  - setuptools=72.1.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py313h06a4308_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.21.0=py313hb8e4a85_0
  - torchmetrics=1.4.0.post0=py313h06a4308_0
  - tqdm=4.67.1=py313h7040dfc_0
  - transformers=4.52.4=pyhd8ed1ab_0
  - typing=3.10.0.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.3.0=py313h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wandb=0.20.1=py313hc85d31f_0
  - wheel=0.45.1=py313h06a4308_0
  - wrapt=1.17.0=py313h5eee18b_0
  - x264=1!157.20191217=h7b6447c_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py313h5eee18b_0
  - zipp=3.21.0=py313h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - cffi==1.17.1
      - mutagen==1.47.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - pillow==11.0.0
      - pycparser==2.22
      - pysoundfile==0.9.0.post1
      - torch==2.7.0+cu118
      - torchaudio==2.7.0+cu118
      - torchvision==0.22.0+cu118
      - triton==3.3.0
prefix: /home/tthebau1/miniconda3/envs/speechllm
